package com.example.unscramblemod.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF006D31)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFF89FAA1)
val md_theme_light_onPrimaryContainer = Color(0xFF00210A)
val md_theme_light_secondary = Color(0xFF4B57A9)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFDFE0FF)
val md_theme_light_onSecondaryContainer = Color(0xFF000E5E)
val md_theme_light_tertiary = Color(0xFF686000)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFF8E500)
val md_theme_light_onTertiaryContainer = Color(0xFF1F1C00)
val md_theme_light_error = Color(0xFFBA1A1A)
val md_theme_light_errorContainer = Color(0xFFFFDAD6)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF410002)
val md_theme_light_background = Color(0xFFFCFDF7)
val md_theme_light_onBackground = Color(0xFF1A1C19)
val md_theme_light_surface = Color(0xFFFCFDF7)
val md_theme_light_onSurface = Color(0xFF1A1C19)
val md_theme_light_surfaceVariant = Color(0xFFDDE5DA)
val md_theme_light_onSurfaceVariant = Color(0xFF414941)
val md_theme_light_outline = Color(0xFF727970)
val md_theme_light_inverseOnSurface = Color(0xFFF0F1EC)
val md_theme_light_inverseSurface = Color(0xFF2E312E)
val md_theme_light_inversePrimary = Color(0xFF6CDD87)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF006D31)
val md_theme_light_outlineVariant = Color(0xFFC1C9BE)
val md_theme_light_scrim = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFF6CDD87)
val md_theme_dark_onPrimary = Color(0xFF003916)
val md_theme_dark_primaryContainer = Color(0xFF005323)
val md_theme_dark_onPrimaryContainer = Color(0xFF89FAA1)
val md_theme_dark_secondary = Color(0xFFBBC3FF)
val md_theme_dark_onSecondary = Color(0xFF192778)
val md_theme_dark_secondaryContainer = Color(0xFF323F90)
val md_theme_dark_onSecondaryContainer = Color(0xFFDFE0FF)
val md_theme_dark_tertiary = Color(0xFFDAC900)
val md_theme_dark_onTertiary = Color(0xFF363100)
val md_theme_dark_tertiaryContainer = Color(0xFF4E4800)
val md_theme_dark_onTertiaryContainer = Color(0xFFF8E500)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF1A1C19)
val md_theme_dark_onBackground = Color(0xFFE2E3DE)
val md_theme_dark_surface = Color(0xFF1A1C19)
val md_theme_dark_onSurface = Color(0xFFE2E3DE)
val md_theme_dark_surfaceVariant = Color(0xFF414941)
val md_theme_dark_onSurfaceVariant = Color(0xFFC1C9BE)
val md_theme_dark_outline = Color(0xFF8B9389)
val md_theme_dark_inverseOnSurface = Color(0xFF1A1C19)
val md_theme_dark_inverseSurface = Color(0xFFE2E3DE)
val md_theme_dark_inversePrimary = Color(0xFF006D31)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFF6CDD87)
val md_theme_dark_outlineVariant = Color(0xFF414941)
val md_theme_dark_scrim = Color(0xFF000000)


val seed = Color(0xFF008C41)
