package com.example.unscramblemod.model

const val MAX_TIME = 60000L
const val COUNT_DOWN = 1000L
const val SCORE_INCREASE = 20
object WordData {

    val wordData = mapOf(
        Pair(1, arrayOf("word","The basic foundation of human communication")),
        Pair(2, arrayOf("animal","Living Organism")),
        Pair(3, arrayOf("auto","abstracting details")),
        Pair(4, arrayOf("alphabet","The foundation of a word")),
        Pair(5, arrayOf("awesome","Joy when amazed by a thing")),
        Pair(6, arrayOf("balloon","pops on too much air intake")),
        Pair(7, arrayOf("basket","We use it to put items when shopping")),
        Pair(8, arrayOf("bench","Where All fun sittings are done")),
        Pair(9, arrayOf("book","Knowledge is passed through generations using it")),
        Pair(10, arrayOf("camera","Captures beautiful scenery around us")),
        Pair(11, arrayOf("cat","The most beautiful in the animal kingdom")),
        Pair(12, arrayOf("boy","A young Man")),
        Pair(13, arrayOf("girl","a young Woman")),
        Pair(14, arrayOf("Aurora","The dawn in the early morning")),
        Pair(15, arrayOf("Bungalow","A type of house with a sloppy roof")),
        Pair(16, arrayOf("Chatoyant","Light reflecting in a gemstone")),
        Pair(17, arrayOf("Eloquence","Ability to beautifully express oneself")),
        Pair(18, arrayOf("Elixir","A (magical) potion")),
        Pair(19, arrayOf("Elegance","High quality of style and class")),
        Pair(20, arrayOf("Eternity","A limitless amount of time")),
        Pair(21, arrayOf("Love","A beautiful feeling of affection")),
        Pair(22, arrayOf("Lithe","Slim and full of grace")),
        Pair(23, arrayOf("Lagoon","A body of water")),
        Pair(24, arrayOf("Melancholy","A feeling a pensive sadness")),
        Pair(25, arrayOf("Mellifluous","Beautifully sounding")),
        Pair(26, arrayOf("Miraculous","Something that is a miracle")),
        Pair(27, arrayOf("Nefarious","Wicked, evil")),
        Pair(28, arrayOf("Nemesis","A rival; an arch-enemy")),
        Pair(29, arrayOf("Oblivion","A state of unawareness of what’s going on around you")),
        Pair(30, arrayOf("Opulence","Luxury, abundance")),
        Pair(31, arrayOf("Paradox","Something that contradicts itself")),
        Pair(32, arrayOf("Peace","A state of freedom in the mind")),
        Pair(33, arrayOf("Pristine","Extremely clean")),
        Pair(34, arrayOf("Quintessence","The most perfect example")),
        Pair(35, arrayOf("Rainbow","An arch of colours in the sky")),
        Pair(36, arrayOf("Ripple","A small movement or wave")),
        Pair(37, arrayOf("Sanguine","Optimistic and positive")),
        Pair(38, arrayOf("Scintilla","A trace or spark of something")),
        Pair(39, arrayOf("Serendipity","A chain of events that occurs in a favorable way")),
        Pair(40, arrayOf("Silhouette","An outline of a figure")),
        Pair(41, arrayOf("Solitude","A state of isolation or loneliness")),
        Pair(42, arrayOf("Tranquility","Another word for peace")),
        Pair(43, arrayOf("Umbrella","The thing you hold to protect yourself from the rain")),
        Pair(44, arrayOf("Wanderlust","A strong desire to travel")),
        Pair(45, arrayOf("Wherewithal","Strength and tenacity")),
        Pair(46, arrayOf("Wistfulness","Yearning or desire")),
        Pair(47, arrayOf("Zenith","The highest, most successful point of a situation")),
        Pair(48, arrayOf("Syzygy","An alignment of 3 celestial bodies")),
        Pair(49, arrayOf("Sumptuous","Rich, luxurious")),
        Pair(50, arrayOf("cherish","care about something and cultivate it with affection")),
        Pair(51, arrayOf("Ephemeral","Short-lived")),
    )

}